/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List available dev login personas
 */
export const ListPersonasResponseItem = zod.object({
  "key": zod.string(),
  "label": zod.string(),
  "role": zod.string(),
  "businessUnitNames": zod.array(zod.string())
})
export const ListPersonasResponse = zod.array(ListPersonasResponseItem)


/**
 * @summary Log in as a dev persona
 */
export const LoginBody = zod.object({
  "persona": zod.string()
})

export const LoginResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.string(),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
}))
})


/**
 * @summary Log out
 */
export const LogoutResponse = zod.void()


/**
 * @summary Get the current authenticated user
 */
export const GetCurrentUserResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.string(),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
}))
})


/**
 * @summary List business units in scope
 */
export const ListBusinessUnitsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "code": zod.string(),
  "isActive": zod.boolean(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListBusinessUnitsResponse = zod.array(ListBusinessUnitsResponseItem)


/**
 * @summary List employees in scope
 */
export const ListEmployeesQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional(),
  "status": zod.coerce.string().optional(),
  "search": zod.coerce.string().optional()
})

export const ListEmployeesResponseItem = zod.object({
  "id": zod.number(),
  "employeeNumber": zod.string(),
  "fullName": zod.string(),
  "email": zod.string(),
  "gender": zod.enum(['M', 'F']),
  "isSaudi": zod.boolean(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "jobTitle": zod.string(),
  "grade": zod.string(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']),
  "hireDate": zod.string(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListEmployeesResponse = zod.array(ListEmployeesResponseItem)


/**
 * @summary Create an employee
 */




export const CreateEmployeeBody = zod.object({
  "employeeNumber": zod.string().min(1),
  "fullName": zod.string().min(1),
  "email": zod.string(),
  "gender": zod.enum(['M', 'F']),
  "isSaudi": zod.boolean(),
  "businessUnitId": zod.number(),
  "jobTitle": zod.string(),
  "grade": zod.string(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']),
  "hireDate": zod.string(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish()
})

export const CreateEmployeeResponse = zod.object({
  "id": zod.number(),
  "employeeNumber": zod.string(),
  "fullName": zod.string(),
  "email": zod.string(),
  "gender": zod.enum(['M', 'F']),
  "isSaudi": zod.boolean(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "jobTitle": zod.string(),
  "grade": zod.string(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']),
  "hireDate": zod.string(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get an employee
 */
export const GetEmployeeParams = zod.object({
  "id": zod.coerce.number()
})

export const GetEmployeeResponse = zod.object({
  "id": zod.number(),
  "employeeNumber": zod.string(),
  "fullName": zod.string(),
  "email": zod.string(),
  "gender": zod.enum(['M', 'F']),
  "isSaudi": zod.boolean(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "jobTitle": zod.string(),
  "grade": zod.string(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']),
  "hireDate": zod.string(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update an employee
 */
export const UpdateEmployeeParams = zod.object({
  "id": zod.coerce.number()
})





export const UpdateEmployeeBody = zod.object({
  "employeeNumber": zod.string().min(1).optional(),
  "fullName": zod.string().min(1).optional(),
  "email": zod.string().optional(),
  "gender": zod.enum(['M', 'F']).optional(),
  "isSaudi": zod.boolean().optional(),
  "businessUnitId": zod.number().optional(),
  "jobTitle": zod.string().optional(),
  "grade": zod.string().optional(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']).optional(),
  "hireDate": zod.string().optional(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish()
})

export const UpdateEmployeeResponse = zod.object({
  "id": zod.number(),
  "employeeNumber": zod.string(),
  "fullName": zod.string(),
  "email": zod.string(),
  "gender": zod.enum(['M', 'F']),
  "isSaudi": zod.boolean(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "jobTitle": zod.string(),
  "grade": zod.string(),
  "employmentStatus": zod.enum(['active', 'on_probation', 'terminated']),
  "hireDate": zod.string(),
  "terminationDate": zod.string().nullish(),
  "managerId": zod.number().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete an employee
 */
export const DeleteEmployeeParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteEmployeeResponse = zod.void()


/**
 * @summary List requisitions in scope
 */
export const ListRequisitionsQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional(),
  "status": zod.coerce.string().optional()
})

export const ListRequisitionsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']),
  "grade": zod.string(),
  "openedDate": zod.string(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListRequisitionsResponse = zod.array(ListRequisitionsResponseItem)


/**
 * @summary Create a requisition
 */



export const CreateRequisitionBody = zod.object({
  "title": zod.string().min(1),
  "businessUnitId": zod.number(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']),
  "grade": zod.string(),
  "openedDate": zod.string(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string()
})

export const CreateRequisitionResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']),
  "grade": zod.string(),
  "openedDate": zod.string(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get a requisition
 */
export const GetRequisitionParams = zod.object({
  "id": zod.coerce.number()
})

export const GetRequisitionResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']),
  "grade": zod.string(),
  "openedDate": zod.string(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update a requisition
 */
export const UpdateRequisitionParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateRequisitionBody = zod.object({
  "title": zod.string().min(1).optional(),
  "businessUnitId": zod.number().optional(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']).optional(),
  "grade": zod.string().optional(),
  "openedDate": zod.string().optional(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string().optional()
})

export const UpdateRequisitionResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "status": zod.enum(['open', 'on_hold', 'filled', 'cancelled']),
  "grade": zod.string(),
  "openedDate": zod.string(),
  "targetCloseDate": zod.string().nullish(),
  "filledDate": zod.string().nullish(),
  "recruiter": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a requisition
 */
export const DeleteRequisitionParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteRequisitionResponse = zod.void()


/**
 * @summary List ER cases in scope
 */
export const ListErCasesQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional(),
  "status": zod.coerce.string().optional()
})

export const ListErCasesResponseItem = zod.object({
  "id": zod.number(),
  "caseNumber": zod.string(),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "caseType": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "status": zod.enum(['open', 'in_progress', 'closed']),
  "openedDate": zod.string(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListErCasesResponse = zod.array(ListErCasesResponseItem)


/**
 * @summary Create an ER case
 */



export const CreateErCaseBody = zod.object({
  "caseNumber": zod.string().min(1),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number(),
  "caseType": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "status": zod.enum(['open', 'in_progress', 'closed']),
  "openedDate": zod.string(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish()
})

export const CreateErCaseResponse = zod.object({
  "id": zod.number(),
  "caseNumber": zod.string(),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "caseType": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "status": zod.enum(['open', 'in_progress', 'closed']),
  "openedDate": zod.string(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get an ER case
 */
export const GetErCaseParams = zod.object({
  "id": zod.coerce.number()
})

export const GetErCaseResponse = zod.object({
  "id": zod.number(),
  "caseNumber": zod.string(),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "caseType": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "status": zod.enum(['open', 'in_progress', 'closed']),
  "openedDate": zod.string(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update an ER case
 */
export const UpdateErCaseParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateErCaseBody = zod.object({
  "caseNumber": zod.string().min(1).optional(),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number().optional(),
  "caseType": zod.string().optional(),
  "severity": zod.enum(['low', 'medium', 'high']).optional(),
  "status": zod.enum(['open', 'in_progress', 'closed']).optional(),
  "openedDate": zod.string().optional(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish()
})

export const UpdateErCaseResponse = zod.object({
  "id": zod.number(),
  "caseNumber": zod.string(),
  "employeeId": zod.number().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "caseType": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "status": zod.enum(['open', 'in_progress', 'closed']),
  "openedDate": zod.string(),
  "closedDate": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete an ER case
 */
export const DeleteErCaseParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteErCaseResponse = zod.void()


/**
 * @summary List attrition records in scope
 */
export const ListAttritionQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const ListAttritionResponseItem = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "attritionType": zod.enum(['voluntary', 'involuntary']),
  "reason": zod.string().nullish(),
  "exitDate": zod.string(),
  "createdAt": zod.string()
})
export const ListAttritionResponse = zod.array(ListAttritionResponseItem)


/**
 * @summary Create an attrition record
 */
export const CreateAttritionBody = zod.object({
  "employeeId": zod.number(),
  "businessUnitId": zod.number(),
  "attritionType": zod.enum(['voluntary', 'involuntary']),
  "reason": zod.string().nullish(),
  "exitDate": zod.string()
})

export const CreateAttritionResponse = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "attritionType": zod.enum(['voluntary', 'involuntary']),
  "reason": zod.string().nullish(),
  "exitDate": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Get an attrition record
 */
export const GetAttritionParams = zod.object({
  "id": zod.coerce.number()
})

export const GetAttritionResponse = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "attritionType": zod.enum(['voluntary', 'involuntary']),
  "reason": zod.string().nullish(),
  "exitDate": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Delete an attrition record
 */
export const DeleteAttritionParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteAttritionResponse = zod.void()


/**
 * @summary List probation records in scope
 */
export const ListProbationQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional(),
  "status": zod.coerce.string().optional()
})

export const ListProbationResponseItem = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListProbationResponse = zod.array(ListProbationResponseItem)


/**
 * @summary Create a probation record
 */
export const CreateProbationBody = zod.object({
  "employeeId": zod.number(),
  "businessUnitId": zod.number(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish()
})

export const CreateProbationResponse = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get a probation record
 */
export const GetProbationParams = zod.object({
  "id": zod.coerce.number()
})

export const GetProbationResponse = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update a probation record
 */
export const UpdateProbationParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateProbationBody = zod.object({
  "startDate": zod.string().optional(),
  "endDate": zod.string().optional(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']).optional(),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish()
})

export const UpdateProbationResponse = zod.object({
  "id": zod.number(),
  "employeeId": zod.number(),
  "employeeName": zod.string().nullish(),
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string().nullish(),
  "startDate": zod.string(),
  "endDate": zod.string(),
  "status": zod.enum(['pending', 'passed', 'failed', 'extended']),
  "reviewDate": zod.string().nullish(),
  "outcome": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a probation record
 */
export const DeleteProbationParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteProbationResponse = zod.void()


/**
 * @summary Get scope-aware KPIs
 */
export const GetDashboardKpisQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetDashboardKpisResponse = zod.object({
  "headcount": zod.number(),
  "saudizationPct": zod.number(),
  "femalePct": zod.number(),
  "openRoles": zod.number(),
  "attritionPct": zod.number(),
  "openErCases": zod.number()
})


/**
 * @summary Compare KPIs across business units (CHRO/Director/Admin)
 */
export const GetDashboardComparisonResponseItem = zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "headcount": zod.number(),
  "saudizationPct": zod.number(),
  "femalePct": zod.number(),
  "openRoles": zod.number(),
  "attritionPct": zod.number(),
  "openErCases": zod.number()
})
export const GetDashboardComparisonResponse = zod.array(GetDashboardComparisonResponseItem)


/**
 * @summary Get monthly headcount and attrition trend
 */
export const GetDashboardTrendsQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetDashboardTrendsResponseItem = zod.object({
  "month": zod.string(),
  "headcount": zod.number(),
  "exits": zod.number()
})
export const GetDashboardTrendsResponse = zod.array(GetDashboardTrendsResponseItem)


/**
 * @summary Business-unit health scores (scope-aware)
 */
export const GetIntelligenceHealthScoresQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetIntelligenceHealthScoresResponseItem = zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "headcount": zod.number(),
  "score": zod.number(),
  "rating": zod.string(),
  "subScores": zod.array(zod.object({
  "key": zod.string(),
  "label": zod.string(),
  "score": zod.number(),
  "weight": zod.number(),
  "value": zod.string()
}))
})
export const GetIntelligenceHealthScoresResponse = zod.array(GetIntelligenceHealthScoresResponseItem)


/**
 * @summary Business-unit workforce risk profiles (scope-aware)
 */
export const GetIntelligenceRiskQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetIntelligenceRiskResponseItem = zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "headcount": zod.number(),
  "workforceRisk": zod.object({
  "score": zod.number(),
  "level": zod.string(),
  "signals": zod.array(zod.object({
  "label": zod.string(),
  "detail": zod.string(),
  "severity": zod.string()
}))
}),
  "attritionRisk": zod.object({
  "score": zod.number(),
  "level": zod.string(),
  "signals": zod.array(zod.object({
  "label": zod.string(),
  "detail": zod.string(),
  "severity": zod.string()
}))
}),
  "recruitmentRisk": zod.object({
  "score": zod.number(),
  "level": zod.string(),
  "signals": zod.array(zod.object({
  "label": zod.string(),
  "detail": zod.string(),
  "severity": zod.string()
}))
}),
  "employeeRelationsRisk": zod.object({
  "score": zod.number(),
  "level": zod.string(),
  "signals": zod.array(zod.object({
  "label": zod.string(),
  "detail": zod.string(),
  "severity": zod.string()
}))
})
})
export const GetIntelligenceRiskResponse = zod.array(GetIntelligenceRiskResponseItem)


/**
 * @summary Cross-business-unit benchmarking (CHRO/Director/Admin)
 */
export const GetIntelligenceBenchmarkingResponse = zod.object({
  "generatedAt": zod.string(),
  "businessUnitCount": zod.number(),
  "metrics": zod.array(zod.object({
  "key": zod.string(),
  "label": zod.string(),
  "unit": zod.string(),
  "higherIsBetter": zod.boolean(),
  "orgAverage": zod.number(),
  "orgMedian": zod.number(),
  "best": zod.union([zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "value": zod.number()
}),zod.null()]),
  "worst": zod.union([zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "value": zod.number()
}),zod.null()]),
  "rows": zod.array(zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "value": zod.number(),
  "rank": zod.number(),
  "percentile": zod.number()
}))
}))
})


/**
 * @summary Executive insights with recommended actions (scope-aware)
 */
export const GetIntelligenceInsightsQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetIntelligenceInsightsResponseItem = zod.object({
  "id": zod.string(),
  "category": zod.string(),
  "severity": zod.string(),
  "title": zod.string(),
  "narrative": zod.string(),
  "businessUnitId": zod.number().nullable(),
  "businessUnitName": zod.string().nullable(),
  "metrics": zod.array(zod.object({
  "label": zod.string(),
  "value": zod.string()
})),
  "recommendedActions": zod.array(zod.string())
})
export const GetIntelligenceInsightsResponse = zod.array(GetIntelligenceInsightsResponseItem)


/**
 * @summary Full workforce context data points (for future AI consumers)
 */
export const GetIntelligenceContextQueryParams = zod.object({
  "businessUnitId": zod.coerce.number().optional()
})

export const GetIntelligenceContextResponse = zod.object({
  "generatedAt": zod.string(),
  "policy": zod.record(zod.string(), zod.number()),
  "scope": zod.object({
  "canSeeAll": zod.boolean(),
  "businessUnitIds": zod.array(zod.number())
}),
  "org": zod.object({
  "businessUnitCount": zod.number(),
  "totalHeadcount": zod.number(),
  "kpis": zod.object({
  "headcount": zod.number(),
  "saudizationPct": zod.number(),
  "femalePct": zod.number(),
  "openRoles": zod.number(),
  "attritionPct": zod.number(),
  "openErCases": zod.number()
}),
  "trends": zod.array(zod.object({
  "month": zod.string(),
  "headcount": zod.number(),
  "exits": zod.number()
})),
  "averageHealthScore": zod.number()
}),
  "businessUnits": zod.array(zod.object({
  "businessUnitId": zod.number(),
  "businessUnitName": zod.string(),
  "kpis": zod.object({
  "headcount": zod.number(),
  "saudizationPct": zod.number(),
  "femalePct": zod.number(),
  "openRoles": zod.number(),
  "attritionPct": zod.number(),
  "openErCases": zod.number()
}),
  "facts": zod.object({
  "headcount": zod.number(),
  "saudiPct": zod.number(),
  "femalePct": zod.number(),
  "attritionPct": zod.number(),
  "exitsLast12mo": zod.number(),
  "exitsRecent3mo": zod.number(),
  "exitsPrior3mo": zod.number(),
  "voluntarySharePct": zod.number(),
  "openRoles": zod.number(),
  "agingRequisitions": zod.number(),
  "avgTimeToFillDays": zod.number().nullable(),
  "openErCases": zod.number(),
  "highSeverityOpenErCases": zod.number(),
  "probationEndingSoon": zod.number(),
  "probationFailRatePct": zod.number()
}),
  "healthScore": zod.number(),
  "healthRating": zod.string(),
  "risk": zod.object({
  "workforce": zod.object({
  "score": zod.number(),
  "level": zod.string()
}),
  "attrition": zod.object({
  "score": zod.number(),
  "level": zod.string()
}),
  "recruitment": zod.object({
  "score": zod.number(),
  "level": zod.string()
}),
  "employeeRelations": zod.object({
  "score": zod.number(),
  "level": zod.string()
})
})
}))
})


/**
 * @summary List users (Admin only)
 */
export const ListUsersResponseItem = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
})),
  "businessUnitIds": zod.array(zod.number()),
  "entraObjectId": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary Create a user (Admin only)
 */




export const CreateUserBody = zod.object({
  "email": zod.string().min(1),
  "displayName": zod.string().min(1),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']),
  "businessUnitIds": zod.array(zod.number()).optional(),
  "isActive": zod.boolean().optional()
})

export const CreateUserResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
})),
  "businessUnitIds": zod.array(zod.number()),
  "entraObjectId": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get a user (Admin only)
 */
export const GetUserParams = zod.object({
  "id": zod.coerce.number()
})

export const GetUserResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
})),
  "businessUnitIds": zod.array(zod.number()),
  "entraObjectId": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Update a user (Admin only)
 */
export const UpdateUserParams = zod.object({
  "id": zod.coerce.number()
})





export const UpdateUserBody = zod.object({
  "email": zod.string().min(1).optional(),
  "displayName": zod.string().min(1).optional(),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']).optional(),
  "businessUnitIds": zod.array(zod.number()).optional(),
  "isActive": zod.boolean().optional()
})

export const UpdateUserResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "displayName": zod.string(),
  "role": zod.enum(['HRBP', 'HR_DIRECTOR', 'CHRO', 'ADMIN']),
  "businessUnits": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string()
})),
  "businessUnitIds": zod.array(zod.number()),
  "entraObjectId": zod.string().nullish(),
  "isActive": zod.boolean(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a user (Admin only)
 */
export const DeleteUserParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteUserResponse = zod.void()


/**
 * @summary List audit log entries (Admin only)
 */
export const ListAuditLogQueryParams = zod.object({
  "entityType": zod.coerce.string().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListAuditLogResponseItem = zod.object({
  "id": zod.number(),
  "actorUserId": zod.number().nullish(),
  "actorName": zod.string().nullish(),
  "action": zod.string(),
  "entityType": zod.string(),
  "entityId": zod.number(),
  "changes": zod.record(zod.string(), zod.unknown()).nullish(),
  "createdAt": zod.string()
})
export const ListAuditLogResponse = zod.array(ListAuditLogResponseItem)


/**
 * @summary List rule-based alerts in scope
 */
export const ListNotificationsResponseItem = zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "severity": zod.enum(['info', 'warning', 'critical']),
  "title": zod.string(),
  "message": zod.string(),
  "businessUnitId": zod.number().nullish(),
  "relatedEntityType": zod.string().nullish(),
  "relatedEntityId": zod.number().nullish(),
  "date": zod.string().nullish()
})
export const ListNotificationsResponse = zod.array(ListNotificationsResponseItem)


