/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type AttritionAttritionType = typeof AttritionAttritionType[keyof typeof AttritionAttritionType];
export declare const AttritionAttritionType: {
    readonly voluntary: "voluntary";
    readonly involuntary: "involuntary";
};
//# sourceMappingURL=attritionAttritionType.d.ts.map