/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type AttritionInputAttritionType = typeof AttritionInputAttritionType[keyof typeof AttritionInputAttritionType];
export declare const AttritionInputAttritionType: {
    readonly voluntary: "voluntary";
    readonly involuntary: "involuntary";
};
//# sourceMappingURL=attritionInputAttritionType.d.ts.map