/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { AttritionInputAttritionType } from './attritionInputAttritionType';
export interface AttritionInput {
    employeeId: number;
    businessUnitId: number;
    attritionType: AttritionInputAttritionType;
    /** @nullable */
    reason?: string | null;
    exitDate: string;
}
//# sourceMappingURL=attritionInput.d.ts.map