/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { AttritionAttritionType } from './attritionAttritionType';
export interface Attrition {
    id: number;
    employeeId: number;
    /** @nullable */
    employeeName?: string | null;
    businessUnitId: number;
    /** @nullable */
    businessUnitName?: string | null;
    attritionType: AttritionAttritionType;
    /** @nullable */
    reason?: string | null;
    exitDate: string;
    createdAt: string;
}
//# sourceMappingURL=attrition.d.ts.map