/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { AuditLogEntryChanges } from './auditLogEntryChanges';

export interface AuditLogEntry {
  id: number;
  /** @nullable */
  actorUserId?: number | null;
  /** @nullable */
  actorName?: string | null;
  action: string;
  entityType: string;
  entityId: number;
  /** @nullable */
  changes?: AuditLogEntryChanges;
  createdAt: string;
}
