/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type AuditLogEntryChanges = {
    [key: string]: unknown;
} | null;
//# sourceMappingURL=auditLogEntryChanges.d.ts.map