/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ContextRiskItem } from './contextRiskItem';

export type BusinessUnitContextRisk = {
  workforce: ContextRiskItem;
  attrition: ContextRiskItem;
  recruitment: ContextRiskItem;
  employeeRelations: ContextRiskItem;
};
