/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface BusinessUnitFacts {
    headcount: number;
    saudiPct: number;
    femalePct: number;
    attritionPct: number;
    exitsLast12mo: number;
    exitsRecent3mo: number;
    exitsPrior3mo: number;
    voluntarySharePct: number;
    openRoles: number;
    agingRequisitions: number;
    /** @nullable */
    avgTimeToFillDays: number | null;
    openErCases: number;
    highSeverityOpenErCases: number;
    probationEndingSoon: number;
    probationFailRatePct: number;
}
//# sourceMappingURL=businessUnitFacts.d.ts.map