/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessUnitContextRisk } from './businessUnitContextRisk';
import type { BusinessUnitFacts } from './businessUnitFacts';
import type { Kpis } from './kpis';

export interface BusinessUnitContext {
  businessUnitId: number;
  businessUnitName: string;
  kpis: Kpis;
  facts: BusinessUnitFacts;
  healthScore: number;
  healthRating: string;
  risk: BusinessUnitContextRisk;
}
