/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type EmployeeInputGender = typeof EmployeeInputGender[keyof typeof EmployeeInputGender];


export const EmployeeInputGender = {
  M: 'M',
  F: 'F',
} as const;
