/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type EmployeeEmploymentStatus = typeof EmployeeEmploymentStatus[keyof typeof EmployeeEmploymentStatus];
export declare const EmployeeEmploymentStatus: {
    readonly active: "active";
    readonly on_probation: "on_probation";
    readonly terminated: "terminated";
};
//# sourceMappingURL=employeeEmploymentStatus.d.ts.map