/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type EmployeeUpdateGender = typeof EmployeeUpdateGender[keyof typeof EmployeeUpdateGender];
export declare const EmployeeUpdateGender: {
    readonly M: "M";
    readonly F: "F";
};
//# sourceMappingURL=employeeUpdateGender.d.ts.map