/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type EmployeeUpdateGender = typeof EmployeeUpdateGender[keyof typeof EmployeeUpdateGender];


export const EmployeeUpdateGender = {
  M: 'M',
  F: 'F',
} as const;
