/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeInputEmploymentStatus } from './employeeInputEmploymentStatus';
import type { EmployeeInputGender } from './employeeInputGender';

export interface EmployeeInput {
  /** @minLength 1 */
  employeeNumber: string;
  /** @minLength 1 */
  fullName: string;
  email: string;
  gender: EmployeeInputGender;
  isSaudi: boolean;
  businessUnitId: number;
  jobTitle: string;
  grade: string;
  employmentStatus: EmployeeInputEmploymentStatus;
  hireDate: string;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  managerId?: number | null;
}
