/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeUpdateEmploymentStatus } from './employeeUpdateEmploymentStatus';
import type { EmployeeUpdateGender } from './employeeUpdateGender';

export interface EmployeeUpdate {
  /** @minLength 1 */
  employeeNumber?: string;
  /** @minLength 1 */
  fullName?: string;
  email?: string;
  gender?: EmployeeUpdateGender;
  isSaudi?: boolean;
  businessUnitId?: number;
  jobTitle?: string;
  grade?: string;
  employmentStatus?: EmployeeUpdateEmploymentStatus;
  hireDate?: string;
  /** @nullable */
  terminationDate?: string | null;
  /** @nullable */
  managerId?: number | null;
}
