/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type EmployeeGender = typeof EmployeeGender[keyof typeof EmployeeGender];
export declare const EmployeeGender: {
    readonly M: "M";
    readonly F: "F";
};
//# sourceMappingURL=employeeGender.d.ts.map