/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type EmployeeInputEmploymentStatus = typeof EmployeeInputEmploymentStatus[keyof typeof EmployeeInputEmploymentStatus];


export const EmployeeInputEmploymentStatus = {
  active: 'active',
  on_probation: 'on_probation',
  terminated: 'terminated',
} as const;
