/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeEmploymentStatus } from './employeeEmploymentStatus';
import type { EmployeeGender } from './employeeGender';
export interface Employee {
    id: number;
    employeeNumber: string;
    fullName: string;
    email: string;
    gender: EmployeeGender;
    isSaudi: boolean;
    businessUnitId: number;
    /** @nullable */
    businessUnitName?: string | null;
    jobTitle: string;
    grade: string;
    employmentStatus: EmployeeEmploymentStatus;
    hireDate: string;
    /** @nullable */
    terminationDate?: string | null;
    /** @nullable */
    managerId?: number | null;
    createdAt: string;
    updatedAt: string;
}
//# sourceMappingURL=employee.d.ts.map