/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type EmployeeInputGender = typeof EmployeeInputGender[keyof typeof EmployeeInputGender];
export declare const EmployeeInputGender: {
    readonly M: "M";
    readonly F: "F";
};
//# sourceMappingURL=employeeInputGender.d.ts.map