/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ErCaseUpdateSeverity = typeof ErCaseUpdateSeverity[keyof typeof ErCaseUpdateSeverity];
export declare const ErCaseUpdateSeverity: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
//# sourceMappingURL=erCaseUpdateSeverity.d.ts.map