/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ErCaseStatus = typeof ErCaseStatus[keyof typeof ErCaseStatus];
export declare const ErCaseStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly closed: "closed";
};
//# sourceMappingURL=erCaseStatus.d.ts.map