/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ErCaseSeverity } from './erCaseSeverity';
import type { ErCaseStatus } from './erCaseStatus';

export interface ErCase {
  id: number;
  caseNumber: string;
  /** @nullable */
  employeeId?: number | null;
  businessUnitId: number;
  /** @nullable */
  businessUnitName?: string | null;
  caseType: string;
  severity: ErCaseSeverity;
  status: ErCaseStatus;
  openedDate: string;
  /** @nullable */
  closedDate?: string | null;
  /** @nullable */
  summary?: string | null;
  createdAt: string;
  updatedAt: string;
}
