/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ErCaseInputStatus = typeof ErCaseInputStatus[keyof typeof ErCaseInputStatus];
export declare const ErCaseInputStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly closed: "closed";
};
//# sourceMappingURL=erCaseInputStatus.d.ts.map