/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ErCaseInputSeverity } from './erCaseInputSeverity';
import type { ErCaseInputStatus } from './erCaseInputStatus';
export interface ErCaseInput {
    /** @minLength 1 */
    caseNumber: string;
    /** @nullable */
    employeeId?: number | null;
    businessUnitId: number;
    caseType: string;
    severity: ErCaseInputSeverity;
    status: ErCaseInputStatus;
    openedDate: string;
    /** @nullable */
    closedDate?: string | null;
    /** @nullable */
    summary?: string | null;
}
//# sourceMappingURL=erCaseInput.d.ts.map