/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ErCaseInputStatus = typeof ErCaseInputStatus[keyof typeof ErCaseInputStatus];


export const ErCaseInputStatus = {
  open: 'open',
  in_progress: 'in_progress',
  closed: 'closed',
} as const;
