/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ErCaseSeverity = typeof ErCaseSeverity[keyof typeof ErCaseSeverity];
export declare const ErCaseSeverity: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
//# sourceMappingURL=erCaseSeverity.d.ts.map