/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ErCaseUpdateSeverity } from './erCaseUpdateSeverity';
import type { ErCaseUpdateStatus } from './erCaseUpdateStatus';

export interface ErCaseUpdate {
  /** @minLength 1 */
  caseNumber?: string;
  /** @nullable */
  employeeId?: number | null;
  businessUnitId?: number;
  caseType?: string;
  severity?: ErCaseUpdateSeverity;
  status?: ErCaseUpdateStatus;
  openedDate?: string;
  /** @nullable */
  closedDate?: string | null;
  /** @nullable */
  summary?: string | null;
}
