/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { InsightMetric } from './insightMetric';
export interface ExecutiveInsight {
    id: string;
    category: string;
    severity: string;
    title: string;
    narrative: string;
    /** @nullable */
    businessUnitId: number | null;
    /** @nullable */
    businessUnitName: string | null;
    metrics: InsightMetric[];
    recommendedActions: string[];
}
//# sourceMappingURL=executiveInsight.d.ts.map