/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type GetIntelligenceContextParams = {
    businessUnitId?: number;
};
//# sourceMappingURL=getIntelligenceContextParams.d.ts.map