/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { SubScore } from './subScore';
export interface HealthScore {
    businessUnitId: number;
    businessUnitName: string;
    headcount: number;
    score: number;
    rating: string;
    subScores: SubScore[];
}
//# sourceMappingURL=healthScore.d.ts.map