/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ListProbationParams = {
    businessUnitId?: number;
    status?: string;
};
//# sourceMappingURL=listProbationParams.d.ts.map