/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type NotificationSeverity = typeof NotificationSeverity[keyof typeof NotificationSeverity];
export declare const NotificationSeverity: {
    readonly info: "info";
    readonly warning: "warning";
    readonly critical: "critical";
};
//# sourceMappingURL=notificationSeverity.d.ts.map