/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationSeverity } from './notificationSeverity';
export interface Notification {
    id: string;
    type: string;
    severity: NotificationSeverity;
    title: string;
    message: string;
    /** @nullable */
    businessUnitId?: number | null;
    /** @nullable */
    relatedEntityType?: string | null;
    /** @nullable */
    relatedEntityId?: number | null;
    /** @nullable */
    date?: string | null;
}
//# sourceMappingURL=notification.d.ts.map