/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type NotificationSeverity = typeof NotificationSeverity[keyof typeof NotificationSeverity];


export const NotificationSeverity = {
  info: 'info',
  warning: 'warning',
  critical: 'critical',
} as const;
