/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ProbationStatus } from './probationStatus';
export interface Probation {
    id: number;
    employeeId: number;
    /** @nullable */
    employeeName?: string | null;
    businessUnitId: number;
    /** @nullable */
    businessUnitName?: string | null;
    startDate: string;
    endDate: string;
    status: ProbationStatus;
    /** @nullable */
    reviewDate?: string | null;
    /** @nullable */
    outcome?: string | null;
    createdAt: string;
    updatedAt: string;
}
//# sourceMappingURL=probation.d.ts.map