/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */

export type ProbationInputStatus = typeof ProbationInputStatus[keyof typeof ProbationInputStatus];


export const ProbationInputStatus = {
  pending: 'pending',
  passed: 'passed',
  failed: 'failed',
  extended: 'extended',
} as const;
