/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ProbationUpdateStatus = typeof ProbationUpdateStatus[keyof typeof ProbationUpdateStatus];
export declare const ProbationUpdateStatus: {
    readonly pending: "pending";
    readonly passed: "passed";
    readonly failed: "failed";
    readonly extended: "extended";
};
//# sourceMappingURL=probationUpdateStatus.d.ts.map