/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type ProbationStatus = typeof ProbationStatus[keyof typeof ProbationStatus];
export declare const ProbationStatus: {
    readonly pending: "pending";
    readonly passed: "passed";
    readonly failed: "failed";
    readonly extended: "extended";
};
//# sourceMappingURL=probationStatus.d.ts.map