/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type RequisitionUpdateStatus = typeof RequisitionUpdateStatus[keyof typeof RequisitionUpdateStatus];
export declare const RequisitionUpdateStatus: {
    readonly open: "open";
    readonly on_hold: "on_hold";
    readonly filled: "filled";
    readonly cancelled: "cancelled";
};
//# sourceMappingURL=requisitionUpdateStatus.d.ts.map