/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { RequisitionUpdateStatus } from './requisitionUpdateStatus';

export interface RequisitionUpdate {
  /** @minLength 1 */
  title?: string;
  businessUnitId?: number;
  status?: RequisitionUpdateStatus;
  grade?: string;
  openedDate?: string;
  /** @nullable */
  targetCloseDate?: string | null;
  /** @nullable */
  filledDate?: string | null;
  recruiter?: string;
}
