/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type RequisitionStatus = typeof RequisitionStatus[keyof typeof RequisitionStatus];
export declare const RequisitionStatus: {
    readonly open: "open";
    readonly on_hold: "on_hold";
    readonly filled: "filled";
    readonly cancelled: "cancelled";
};
//# sourceMappingURL=requisitionStatus.d.ts.map