/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { RequisitionStatus } from './requisitionStatus';
export interface Requisition {
    id: number;
    title: string;
    businessUnitId: number;
    /** @nullable */
    businessUnitName?: string | null;
    status: RequisitionStatus;
    grade: string;
    openedDate: string;
    /** @nullable */
    targetCloseDate?: string | null;
    /** @nullable */
    filledDate?: string | null;
    recruiter: string;
    createdAt: string;
    updatedAt: string;
}
//# sourceMappingURL=requisition.d.ts.map