/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { RiskSignal } from './riskSignal';
export interface RiskMetric {
    score: number;
    level: string;
    signals: RiskSignal[];
}
//# sourceMappingURL=riskMetric.d.ts.map