/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { RiskMetric } from './riskMetric';
export interface RiskProfile {
    businessUnitId: number;
    businessUnitName: string;
    headcount: number;
    workforceRisk: RiskMetric;
    attritionRisk: RiskMetric;
    recruitmentRisk: RiskMetric;
    employeeRelationsRisk: RiskMetric;
}
//# sourceMappingURL=riskProfile.d.ts.map