/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface TrendPoint {
    month: string;
    headcount: number;
    exits: number;
}
//# sourceMappingURL=trendPoint.d.ts.map