/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type UserInputRole = typeof UserInputRole[keyof typeof UserInputRole];
export declare const UserInputRole: {
    readonly HRBP: "HRBP";
    readonly HR_DIRECTOR: "HR_DIRECTOR";
    readonly CHRO: "CHRO";
    readonly ADMIN: "ADMIN";
};
//# sourceMappingURL=userInputRole.d.ts.map