/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];
export declare const UserRole: {
    readonly HRBP: "HRBP";
    readonly HR_DIRECTOR: "HR_DIRECTOR";
    readonly CHRO: "CHRO";
    readonly ADMIN: "ADMIN";
};
//# sourceMappingURL=userRole.d.ts.map