/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type UserUpdateRole = typeof UserUpdateRole[keyof typeof UserUpdateRole];
export declare const UserUpdateRole: {
    readonly HRBP: "HRBP";
    readonly HR_DIRECTOR: "HR_DIRECTOR";
    readonly CHRO: "CHRO";
    readonly ADMIN: "ADMIN";
};
//# sourceMappingURL=userUpdateRole.d.ts.map