/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateRole } from './userUpdateRole';
export interface UserUpdate {
    /** @minLength 1 */
    email?: string;
    /** @minLength 1 */
    displayName?: string;
    role?: UserUpdateRole;
    businessUnitIds?: number[];
    isActive?: boolean;
}
//# sourceMappingURL=userUpdate.d.ts.map