/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessUnitContext } from './businessUnitContext';
import type { WorkforceContextOrg } from './workforceContextOrg';
import type { WorkforceContextPolicy } from './workforceContextPolicy';
import type { WorkforceContextScope } from './workforceContextScope';
export interface WorkforceContext {
    generatedAt: string;
    policy: WorkforceContextPolicy;
    scope: WorkforceContextScope;
    org: WorkforceContextOrg;
    businessUnits: BusinessUnitContext[];
}
//# sourceMappingURL=workforceContext.d.ts.map