/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Enterprise HRBP Platform API
 * OpenAPI spec version: 0.1.0
 */
export type WorkforceContextPolicy = {
    [key: string]: number;
};
//# sourceMappingURL=workforceContextPolicy.d.ts.map